# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: Hiddify.Next
PackageVersion: 0.11.1
InstallerType: zip
NestedInstallerType: inno
NestedInstallerFiles:
- RelativeFilePath: setup.exe
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/hiddify/hiddify-next/releases/download/v0.11.1/hiddify-windows-x64-setup.zip
  InstallerSha256: 3656882957A449248688C8E46EAC2BDC97A5682A75E13B85BC749517BEAFB35F
ManifestType: installer
ManifestVersion: 1.5.0
